# Generated by Django 5.1.1 on 2024-10-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='subscriberequest',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
