# Generated by Django 3.2.25 on 2024-10-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_remove_subscribe_image_remove_subscribe_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberequest',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email is already subscribed.'}, max_length=254, unique=True),
        ),
    ]
