# Generated by Django 3.2.25 on 2024-10-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20241030_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Trouble using the site', 'Trouble using the site'), ('Ticket Issues', 'Account Issues'), ('Event Issues', 'Event Issues'), ('Other', 'Other')], default='Other', max_length=254),
        ),
    ]
