# Generated by Django 3.2.25 on 2024-09-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
