# Generated by Django 4.2.16 on 2024-11-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
