# Generated by Django 4.2.16 on 2024-11-02 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
